#!/usr/bin/env bash
# init-plan-dirs.sh — Initialize the docs/plans directory structure
# Usage: bash init-plan-dirs.sh [project_root]

set -euo pipefail

PROJECT_ROOT="${1:-.}"

mkdir -p "$PROJECT_ROOT/docs/plans/agent-outputs"
mkdir -p "$PROJECT_ROOT/docs/plans/research"
mkdir -p "$PROJECT_ROOT/docs/plans/execution-log"

# Create goal-analysis template if it doesn't exist
if [ ! -f "$PROJECT_ROOT/docs/plans/goal-analysis.md" ]; then
    cat > "$PROJECT_ROOT/docs/plans/goal-analysis.md" << 'TEMPLATE'
# Goal Analysis

> This document is the canonical reference for all planning agents.
> Generated by team-executor Phase 1, Step 1.

## Organized Goals

<!-- Numbered, deduplicated, logically ordered goals -->

## Dependencies Between Goals

<!-- Which goals depend on others -->

## Inferred Requirements

<!-- Requirements not explicitly stated but logically necessary -->
<!-- Mark each with [INFERRED] so agents know these weren't in the original input -->

## Constraints & Boundaries

<!-- Technical constraints, business rules, scope limits -->

## Open Questions

<!-- Anything that R&D agents should investigate -->
TEMPLATE
    echo "Created: $PROJECT_ROOT/docs/plans/goal-analysis.md"
fi

echo "Plan directories initialized at $PROJECT_ROOT/docs/plans/"
